gz_worlds_dir: /home/vojta/PX4/PX4-Autopilot/Tools/simulation/gz/worlds
base_world_path: ./GUI/base.sdf
px4_bin_path: "/home/vojta/PX4/PX4-Autopilot/build/px4_sitl_default/bin/px4"
gz_model: x500_cam
px4_sys_autostart: '4001'
camera:
  fx: 614.1182502063649
  fy: 614.2811984891936
  cx: 289.5307050411072
  cy: 239.48850240020735
uav_h: 10
max_steps_wo_visual: 50
landing_trigger_alt: 0.5
uav_max_v: 1.5 # m/s
exclude_mission_columns_in_experiment_table: ["plosina.stin_sklon", "plosina.phi", "vitr.s_phi", "vitr.s_v", "uav.phi"]
experiments_file: GUI/experimenty.yaml
default_mission_repeats: 1
sample_mission: {algoritmus: "", nazev: "", plosina: {a: 0, phi: 0, stin: 0, stin_sklon: 0, x: 0, y: 0}, uav: {phi: 0.0, x: 0.0, y: 0.0}, vitr: {phi: 0.0, s_phi: 0.0, s_v: 0, v: 0}}