gz_worlds_dir: /home/vojta/PX4/PX4-Autopilot/Tools/simulation/gz/worlds
base_world_path: ./GUI/base.sdf
px4_bin_path: "/home/vojta/PX4/PX4-Autopilot/build/px4_sitl_default/bin/px4"
gz_model: x500_cam
px4_sys_autostart: '4001'
restart_after_experiments: 1
headless: True
camera:
  fx: 614.1182502063649
  fy: 614.2811984891936
  cx: 289.5307050411072
  cy: 239.48850240020735
  height_offset: 0.1
  x_offset: 0
  y_offset: 0
  # x_offset: -0.12
  # y_offset: 0.4
sun_direction: [-0.5, 0.1, -0.7]
uav_h: 10
max_steps_wo_visual: 50
landing_trigger_alt: 0.60
uav_max_v: 1.5 # m/s
exclude_mission_columns_in_experiment_table: ["plosina.stin_sklon", "plosina.phi", "vitr.s_phi", "vitr.s_v", "uav.phi"]
experiments_file: GUI/experimenty.yaml
default_mission_repeats: 1
sample_mission: {algoritmus: "", nazev: "", plosina: {a: 0, phi: 0, stin: 0, stin_sklon: 0, x: 0, y: 0}, uav: {phi: 0.0, x: 0.0, y: 0.0}, vitr: {phi: 0.0, s_phi: 0.0, s_v: 0, v: 0}}
origin:
  lat_deg: 49.723888888
  lon_deg: 13.36583333333
  elevation: 345.8
kalman:
  P: [[ 0.03014223,  0,        -0.00030722, 0,          0.01661176, 0,     -0.00163876, 0],
      [ 0,           0.005,     0,          0,          0,          0,      0,          0],
      [-0.00030722,  0,         0.0167032,  0,         -0.00242127, 0,      0.00788586, 0],
      [ 0,           0,         0,          0.005,      0,          0,      0,          0],
      [ 0.01661176,  0,        -0.00242127, 0,          0.05197746, 0,      0.00966988, 0],
      [ 0,           0,         0,          0,          0,          0.02,   0,          0],
      [-0.00163876,  0,         0.00788586, 0,          0.00966988, 0,      0.17439375, 0],
      [ 0,           0,         0,          0,          0,          0,      0,          0.07]]
  Q: [[ 0,           0,         0,          0,          0,          0,      0,          0],
      [ 0,           0.002,     0,          0,          0,          0,      0,          0],
      [ 0,           0,         0,          0,          0,          0,      0,          0],
      [ 0,           0,         0,          0.002,      0,          0,      0,          0],
      [ 0,           0,         0,          0,          0,          0,      0,          0],
      [ 0,           0,         0,          0,          0,          0.004,  0,          0],
      [ 0,           0,         0,          0,          0,          0,      0,          0],
      [ 0,           0,         0,          0,          0,          0,      0,          0.02]]
  R: [[ 0.0115046,  -0.0027762,   0.00556524, -0.00916558],
      [-0.0027762,   0.01485437, -0.00325932, -0.0112056 ],
      [ 0.00556524, -0.00325932,  0.02560924, -0.00258199],
      [-0.00916558, -0.0112056,  -0.00258199,  1.89420811]]
  F: [[ 1.00000,     0.03333, 0.0,     0.0,     0.0,     0.0,     0.0,     0.0    ],
      [     0.0,     1.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0    ],
      [     0.0,     0.0,     1.0,     0.03333, 0.0,     0.0,     0.0,     0.0    ],
      [     0.0,     0.0,     0.0,     1.0,     0.0,     0.0,     0.0,     0.0    ],
      [     0.0,     0.0,     0.0,     0.0,     1.0,     0.03333, 0.0,     0.0    ],
      [     0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     0.0,     0.0    ],
      [     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     0.03333],
      [     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0    ]]
  B: [[0.000555, 0.0,      0.0,      0.0,      ],
      [0.033333, 0.0,      0.0,      0.0,      ],
      [0.0,      0.000555, 0.0,      0.0,      ],
      [0.0,      0.033333, 0.0,      0.0,      ],
      [0.0,      0.0,      0.000555, 0.0,      ],
      [0.0,      0.0,      0.033333, 0.0,      ],
      [0.0,      0.0,      0.0,      0.000555  ],
      [0.0,      0.0,      0.0,      0.033333  ],]
  H: [[ 1.00000,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     0.0    ],
      [     0.0,     0.0,     1.0,     0.0,     0.0,     0.0,     0.0,     0.0    ],
      [     0.0,     0.0,     0.0,     0.0,     1.0,     0.00000, 0.0,     0.0    ],
      [     0.0,     0.0,     0.0,     0.0,     0.0,     0.0,     1.0,     0.00000]]